## Nation

**TODO**: 
  1. Add an `end_year` parameter, and make all functions use it, so this is easier to update when new data comes in.
  2. Add places and MSAs
  3. Convert this into a script that can be run with a single command.

In [1]:
from acs_nativity import get_nativity_timeseries

In [ ]:
df_us = get_nativity_timeseries(us="*")
df_us

...................

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,United States,2005,288378137,252688295,35689842,12.376057
1,United States,2006,299398485,261850696,37547789,12.541075
2,United States,2007,301621159,263561465,38059694,12.618377
3,United States,2008,304059728,266098793,37960935,12.484697
4,United States,2009,307006556,268489322,38517234,12.546062
5,United States,2010,309349689,269393835,39955854,12.916080
6,United States,2011,311591919,271214059,40377860,12.958571
7,United States,2012,313914040,273089382,40824658,13.005044
8,United States,2013,316128839,274780773,41348066,13.079498
9,United States,2014,318857056,276465262,42391794,13.294921
10,United States,2015,321418821,278128449,43290372,13.468524
11,United States,2016,323127515,279388170,43739345,13.536249
12,United States,2017,325719178,281193323,44525855,13.670013
13,United States,2018,327167439,282438718,44728721,13.671508
14,United States,2019,328239523,283306622,44932901,13.689059
15,United States,2021,331893745,286623642,45270103,13.639939
16,United States,2022,333287562,287105385,46182177,13.856556
17,United States,2023,334914896,287083485,47831411,14.281661
18,United States,2024,340110990,289876132,50234858,14.770137

In [2]:
df_us.to_csv("us.csv", index=False)

## State

In [5]:
df_state = get_nativity_timeseries(state="*")
df_state

...................

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,Alabama,2005,4442558.0,4321785.0,120773.0,2.718546
1,Alaska,2005,641724.0,607356.0,34368.0,5.355573
2,Arizona,2005,5829839.0,4986543.0,843296.0,14.465168
3,Arkansas,2005,2701431.0,2600262.0,101169.0,3.745015
4,California,2005,35278768.0,25667412.0,9611356.0,27.244024
...,...,...,...,...,...,...
983,Washington,2024,7958180.0,6677371.0,1280809.0,16.094245
984,West Virginia,2024,1769979.0,1732726.0,37253.0,2.104714
985,Wisconsin,2024,5960975.0,5633942.0,327033.0,5.486233
986,Wyoming,2024,587618.0,567162.0,20456.0,3.481173
987,Puerto Rico,2024,NaN,NaN,NaN,NaN

In [31]:
df_state = df_state[df_state["Name"] != "Puerto Rico"]
df_state

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,Alabama,2005,4442558.0,4321785.0,120773.0,2.718546
1,Alaska,2005,641724.0,607356.0,34368.0,5.355573
2,Arizona,2005,5829839.0,4986543.0,843296.0,14.465168
3,Arkansas,2005,2701431.0,2600262.0,101169.0,3.745015
4,California,2005,35278768.0,25667412.0,9611356.0,27.244024
...,...,...,...,...,...,...
982,Virginia,2024,8811195.0,7617614.0,1193581.0,13.546188
983,Washington,2024,7958180.0,6677371.0,1280809.0,16.094245
984,West Virginia,2024,1769979.0,1732726.0,37253.0,2.104714
985,Wisconsin,2024,5960975.0,5633942.0,327033.0,5.486233
986,Wyoming,2024,587618.0,567162.0,20456.0,3.481173

In [34]:
df_state["Name"].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [36]:
df_state.to_csv("state.csv", index=False)

## County

In [7]:
from censusdis import states
import pandas as pd

dfs = []
for state in states.ALL_STATES_AND_DC:
    print(f"Getting data for {states.NAMES_FROM_IDS[state]}")
    df_new = get_nativity_timeseries(state=state, county="*")
    print(f"Num rows is {len(df_new)}")
    dfs.append(df_new)

df_county = pd.concat(dfs)
df_county.to_csv("county.csv", index=False)
df_county

Getting data for Alabama
...................Num rows is 396
Getting data for Alaska
...................Num rows is 57
Getting data for Arizona
...................Num rows is 190
Getting data for Arkansas
...................Num rows is 206
Getting data for California
...................Num rows is 769
Getting data for Colorado
...................Num rows is 218
Getting data for Connecticut
...................Num rows is 155
Getting data for District of Columbia
...................Num rows is 19
Getting data for Delaware
...................Num rows is 57
Getting data for Florida
...................Num rows is 765
Getting data for Georgia
...................Num rows is 672
Getting data for Hawaii
...................Num rows is 71
Getting data for Idaho
...................Num rows is 114
Getting data for Illinois
...................Num rows is 429
Getting data for Indiana
...................Num rows is 484
Getting data for Iowa
...................Num rows is 185
Getting data for Kansas
...................Num rows is 145
Getting data for Kentucky
...................Num rows is 248
Getting data for Louisiana
...................Num rows is 324
Getting data for Maine
...................Num rows is 114
Getting data for Maryland
...................Num rows is 304
Getting data for Massachusetts
...................Num rows is 228
Getting data for Minnesota
...................Num rows is 260
Getting data for Mississippi
...................Num rows is 194
Getting data for Michigan
...................Num rows is 554
Getting data for Missouri
...................Num rows is 319
Getting data for Montana
...................Num rows is 106
Getting data for Nebraska
...................Num rows is 57
Getting data for Nevada
...................Num rows is 38
Getting data for New Hampshire
...................Num rows is 116
Getting data for New Jersey
...................Num rows is 399
Getting data for New Mexico
...................Num rows is 169
Getting data for New York
...................Num rows is 732
Getting data for North Carolina
...................Num rows is 756
Getting data for North Dakota
...................Num rows is 68
Getting data for Ohio
...................Num rows is 726
Getting data for Oklahoma
...................Num rows is 208
Getting data for Oregon
...................Num rows is 285
Getting data for Pennsylvania
...................Num rows is 752
Getting data for Rhode Island
...................Num rows is 76
Getting data for South Carolina
...................Num rows is 402
Getting data for South Dakota
...................Num rows is 42
Getting data for Tennessee
...................Num rows is 380
Getting data for Texas
...................Num rows is 1004
Getting data for Utah
...................Num rows is 122
Getting data for Vermont
...................Num rows is 19
Getting data for Virginia
...................Num rows is 559
Getting data for Washington
...................Num rows is 366
Getting data for West Virginia
...................Num rows is 133
Getting data for Wisconsin
...................Num rows is 445
Getting data for Wyoming
...................Num rows is 38

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,"Baldwin County, Alabama",2005,160354.0,155982.0,4372.0,2.726468
1,"Calhoun County, Alabama",2005,109762.0,107543.0,2219.0,2.021647
2,"Cullman County, Alabama",2005,78888.0,77073.0,1815.0,2.300730
3,"DeKalb County, Alabama",2005,66407.0,63325.0,3082.0,4.641077
4,"Elmore County, Alabama",2005,68057.0,67262.0,795.0,1.168138
...,...,...,...,...,...,...
33,"Natrona County, Wyoming",2022,79601.0,77875.0,1726.0,2.168314
34,"Laramie County, Wyoming",2023,100984.0,97853.0,3131.0,3.100491
35,"Natrona County, Wyoming",2023,79941.0,77282.0,2659.0,3.326203
36,"Laramie County, Wyoming",2024,101783.0,98734.0,3049.0,2.995589
37,"Natrona County, Wyoming",2024,80410.0,78793.0,1617.0,2.010944

In [ ]:
# Assert all names have exactly 1 comma. i.e. "county, state"
num_commas = df_county["Name"].str.count(",")
(num_commas == 1).all()

False

In [19]:
df_county

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,"Baldwin County, Alabama",2005,160354.0,155982.0,4372.0,2.726468
1,"Calhoun County, Alabama",2005,109762.0,107543.0,2219.0,2.021647
2,"Cullman County, Alabama",2005,78888.0,77073.0,1815.0,2.300730
3,"DeKalb County, Alabama",2005,66407.0,63325.0,3082.0,4.641077
4,"Elmore County, Alabama",2005,68057.0,67262.0,795.0,1.168138
...,...,...,...,...,...,...
33,"Natrona County, Wyoming",2022,79601.0,77875.0,1726.0,2.168314
34,"Laramie County, Wyoming",2023,100984.0,97853.0,3131.0,3.100491
35,"Natrona County, Wyoming",2023,79941.0,77282.0,2659.0,3.326203
36,"Laramie County, Wyoming",2024,101783.0,98734.0,3049.0,2.995589
37,"Natrona County, Wyoming",2024,80410.0,78793.0,1617.0,2.010944

In [28]:
df_county[["County", "State"]] = df_county["Name"].str.split(",", expand=True)
df_county["County"] = df_county["County"].str.strip()
df_county["State"] = df_county["State"].str.strip()
df_county = df_county[
    [
        "State",
        "County",
        "Name",
        "Year",
        "Total",
        "Native",
        "Foreign-born",
        "Percent Foreign-born",
    ]
]

df_county

,State,County,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,Alabama,Baldwin County,"Baldwin County, Alabama",2005,160354.0,155982.0,4372.0,2.726468
1,Alabama,Calhoun County,"Calhoun County, Alabama",2005,109762.0,107543.0,2219.0,2.021647
2,Alabama,Cullman County,"Cullman County, Alabama",2005,78888.0,77073.0,1815.0,2.300730
3,Alabama,DeKalb County,"DeKalb County, Alabama",2005,66407.0,63325.0,3082.0,4.641077
4,Alabama,Elmore County,"Elmore County, Alabama",2005,68057.0,67262.0,795.0,1.168138
...,...,...,...,...,...,...,...,...
33,Wyoming,Natrona County,"Natrona County, Wyoming",2022,79601.0,77875.0,1726.0,2.168314
34,Wyoming,Laramie County,"Laramie County, Wyoming",2023,100984.0,97853.0,3131.0,3.100491
35,Wyoming,Natrona County,"Natrona County, Wyoming",2023,79941.0,77282.0,2659.0,3.326203
36,Wyoming,Laramie County,"Laramie County, Wyoming",2024,101783.0,98734.0,3049.0,2.995589
37,Wyoming,Natrona County,"Natrona County, Wyoming",2024,80410.0,78793.0,1617.0,2.010944

In [29]:
df_county.to_csv("county.csv", index=False)

## Places

In [6]:
from acs_nativity import get_nativity_timeseries
from censusdis import states
import pandas as pd

# Census only includes data for places with population >=65k.
# For at least for some years these states have had no data,
# and this causes censusdis to throw a 204 error.
# For now it's best to just skip these states.
NO_DATA_STATES = [states.ME, states.VT, states.WV, states.WY]

dfs = []
for state in states.ALL_STATES_AND_DC:
    if state in NO_DATA_STATES:
        print(f"Skipping {states.NAMES_FROM_IDS[state]} due to low population")
        continue
    print(f"Getting data for {states.NAMES_FROM_IDS[state]}")
    df_new = get_nativity_timeseries(state=state, place="*")
    print(f"Num rows is {len(df_new)}")
    dfs.append(df_new)

df_place = pd.concat(dfs)
df_place.to_csv("place.csv", index=False)
df_place

Getting data for Alabama
...................Num rows is 138
Getting data for Alaska
...................Num rows is 19
Getting data for Arizona
...................Num rows is 298
Getting data for Arkansas
...................Num rows is 112
Getting data for California
...................Num rows is 2539
Getting data for Colorado
...................Num rows is 304
Getting data for Connecticut
...................Num rows is 152
Getting data for District of Columbia
...................Num rows is 19
Getting data for Delaware
...................Num rows is 19
Getting data for Florida
...................Num rows is 910
Getting data for Georgia
...................Num rows is 217
Getting data for Hawaii
...................Num rows is 19
Getting data for Idaho
...................Num rows is 61
Getting data for Illinois
...................Num rows is 360
Getting data for Indiana
...................Num rows is 205
Getting data for Iowa
...................Num rows is 133
Getting data for Kansas
...................Num rows is 123
Getting data for Kentucky
...................Num rows is 46
Getting data for Louisiana
...................Num rows is 140
Skipping Maine due to low population
Getting data for Maryland
...................Num rows is 158
Getting data for Massachusetts
...................Num rows is 276
Getting data for Minnesota
...................Num rows is 197
Getting data for Mississippi
...................Num rows is 38
Getting data for Michigan
...................Num rows is 337
Getting data for Missouri
...................Num rows is 167
Getting data for Montana
...................Num rows is 36
Getting data for Nebraska
...................Num rows is 38
Getting data for Nevada
...................Num rows is 170
Getting data for New Hampshire
...................Num rows is 38
Getting data for New Jersey
...................Num rows is 230
Getting data for New Mexico
...................Num rows is 76
Getting data for New York
...................Num rows is 191
Getting data for North Carolina
...................Num rows is 266
Getting data for North Dakota
...................Num rows is 30
Getting data for Ohio
...................Num rows is 186
Getting data for Oklahoma
...................Num rows is 114
Getting data for Oregon
...................Num rows is 152
Getting data for Pennsylvania
...................Num rows is 133
Getting data for Rhode Island
...................Num rows is 76
Getting data for South Carolina
...................Num rows is 97
Getting data for South Dakota
...................Num rows is 35
Getting data for Tennessee
...................Num rows is 151
Getting data for Texas
...................Num rows is 1061
Getting data for Utah
...................Num rows is 184
Skipping Vermont due to low population
Getting data for Virginia
...................Num rows is 261
Getting data for Washington
...................Num rows is 303
Skipping West Virginia due to low population
Getting data for Wisconsin
...................Num rows is 167
Skipping Wyoming due to low population

,Name,Year,Total,Native,Foreign-born,Percent Foreign-born
0,"Birmingham city, Alabama",2005,222154.0,212484.0,9670.0,4.352836
1,"Hoover city, Alabama",2005,74473.0,68897.0,5576.0,7.487277
2,"Huntsville city, Alabama",2005,158618.0,149595.0,9023.0,5.688510
3,"Mobile city, Alabama",2005,193332.0,185567.0,7765.0,4.016407
4,"Montgomery city, Alabama",2005,193042.0,186907.0,6135.0,3.178065
...,...,...,...,...,...,...
162,"Madison city, Wisconsin",2024,285318.0,254019.0,31299.0,10.969865
163,"Milwaukee city, Wisconsin",2024,563512.0,496163.0,67349.0,11.951653
164,"Oshkosh city, Wisconsin",2024,67241.0,64011.0,3230.0,4.803617
165,"Racine city, Wisconsin",2024,78063.0,72189.0,5874.0,7.524692
166,"Waukesha city, Wisconsin",2024,71462.0,66118.0,5344.0,7.478100

In [5]:
get_nativity_timeseries(state=states.WY, place="*")

.

CensusApiException: Census API request to https://api.census.gov/data/2005/acs/acs1?get=B05002_001E%2CB05002_002E%2CB05002_003E%2CB05002_004E%2CB05002_005E%2CB05002_006E%2CB05002_007E%2CB05002_008E%2CB05002_009E%2CB05002_010E%2CB05002_011E%2CB05002_012E%2CB05002_013E%2CB05002_014E%2CB05002_015E%2CGEO_ID%2CNAME&for=place&in=state%3A56&key=f8b2a6df01479981aef39577b3c4466f5a4c8274 failed with status 204.

## MSAs